### ISSUE TITLE
Is it possible to define multiple authorizers for a single method?

### ISSUE THREAD

**Issue by ziomio** [nathanl/authority#109]
Problem described here:
http://stackoverflow.com/questions/35740710/is-it-possible-to-define-multiple-authorizers-for-a-single-method

**Comment by djothefou** [comment]
The stackoverflow's link is out of dated.

**Comment by nathanl** [comment]
I don't understand the use case. However, your goal should be to push all complexity around authorization out of your controllers and into your authorizers.

You can define authorizers that do anything you need. They can call other authorizers, they can use any inheritance or composition pattern you like, or they can check the weather via an API and reject requests from users in cloudy areas. 😄  Don't try to do too much in a controller.
