### ISSUE TITLE
Log all authorization attempts?

### ISSUE THREAD

**Issue by nathanl** [nathanl/authority#118]
I got a question via Twitter and thought it would be best to make it a discussion here:

> any recommendations for logging all authorization attempts via authority?

**Comment by nathanl** [comment]
Logging *all* authorization attempts would currently require modifying Authority, either as a monkey patch or a PR.

Here's how logging is currently done.

First, [this code](https://github.com/nathanl/authority/blob/3b4ef014ec60070f303e638b6e917d2bedb94dc9/lib/authority.rb#L36-L40) raises an exception.

Then [this code](https://github.com/nathanl/authority/blob/3b4ef014ec60070f303e638b6e917d2bedb94dc9/lib/authority/controller.rb#L8-L17) rescues the exception and calls your configured `security_violation_handler`.

[By default](https://github.com/nathanl/authority/blob/3b4ef014ec60070f303e638b6e917d2bedb94dc9/lib/authority/configuration.rb#L29), that's the `:authority_forbidden` method, which [logs the violation and renders a 403](https://github.com/nathanl/authority/blob/3b4ef014ec60070f303e638b6e917d2bedb94dc9/lib/authority/controller.rb#L142-L145).

So to log all attempts at authorization, successful or not, would require modifying [Authority.enforce](https://github.com/nathanl/authority/blob/3b4ef014ec60070f303e638b6e917d2bedb94dc9/lib/authority.rb#L36-L40) to have it log in both cases. Eg, it could do `Authority.logger.info("#{user} is attempting to #{action} #{resource} with options #{options}"`, and there could be a second `warn` log entry if that fails.

That's not a hard change, but I don't know if any users would object to having those extra log messages. We could configure whether to log in that case, but more options == more complexity, so IDK.

**Comment by forced-request** [comment]
Thanks @nathanl. I think it's good to have the option. This allows developers to better audit user actions. I would probably have this disabled by default, and be enabled via the rollbar initializer.

**Comment by nathanl** [comment]
@forced-request I can see why you'd want to be able to log everything. Interested in making a PR?

**Comment by forced-request** [comment]
I should be able to make that happen. I'll get back to you soon.

**Comment by nathanl** [comment]
Fixed in https://github.com/nathanl/authority/pull/119
