### ISSUE TITLE
Authorization with Rails Admin Gem

### ISSUE THREAD

**Issue by bhushangahire** [nathanl/authority#121]
How I can integrate this with rails_admin gem ?

**Comment by nathanl** [comment]
I haven't tried it. Does https://github.com/sferik/rails_admin/wiki/Customized-authorization help you?

**Comment by bhushangahire** [comment]
I had to use role-based customization for each model. I moved to Cancancan.

**Comment by nathanl** [comment]
There's no reason you can't check roles in an Authority authorizer or in a Pundit policy, but perhaps rails_admin doesn't make it as easy to use them?
