### ISSUE TITLE
Could we use authority with active model serializer ?

### ISSUE THREAD

**Issue by imadmoussa1** [nathanl/authority#122]
Hello  @nathanl ,

I am using the active model serializer (json_api ). When we make a call to the api, the response will include the associations and relations.
`render json: @articles, include: '*'`
However when the user in not authorized to "read" the relation model, I do not want to include the relation in the response .

Can we handle this case using Authority gem ?

thank you.

**Comment by nathanl** [comment]
There's no special support for this, but you can ask `relation_model.authorizer.readable_by?(user)` if that makes sense in your app.
