### ISSUE TITLE
Help with maintenance?

### ISSUE THREAD

**Issue by nathanl** [nathanl/authority#94]
Hello there, friends of Authority. :) I'm going to mention you all to get your attention.

@mguymon @kevmoo @adamhunter @MP211 @sanemat @div @christhekeele @gergoerdosi @capicue @scottmartin @awinograd @binarypaladin 

In the last year, I haven't used Authority at all, just because of the kind of projects I'm doing. Lately, when PRs come in or questions on usage, I have to try to remember how things are supposed to work. I've been letting issues sit for too long. In other words, I'm not the best maintainer right now.

I'm sure you're all busy, so feel free to ignore this, but each of you lovely folks has contributed to the project in the past. If you'd like to have a commit bit on the project or take a more active role in answering issues, I'd love to have some help.

Anyone?

**Comment by binarypaladin** [comment]
I'm not super familiar with the codebase right now, however I'm working on a project that makes heavy use of this. I'm going to have a discussion about "adopting" the project shortly (probably next week) and see if that yields anything.

I'd love to help either way.

**Comment by nathanl** [comment]
Yaaaaaay! :clap: :clap: :smile: Thank you!

If you dive into the codebase and find anything confusing, please open an issue and let's make it clearer.

**Comment by nathanl** [comment]
Also, yay for @sanemat doing this: https://github.com/nathanl/authority/pull/95!

**Comment by nathanl** [comment]
I've just made @sanemat a collaborator on the project and am open to adding others. Here's my thoughts on how we can work together:

- I'd love to have help answering issues
- I'd like to give a commit bit to some of you (as I've just done for sanemat)
- If you get a commit bit, feel free to do small things like fixing typos on master, but let's use pull requests for anything bigger. I'll do the same.
- At least for now, I'm going to keep the ability to actually release to rubygems restricted to me and @adamhunter (my friend in real life). I feel I must take responsibility for that, because releasing means shipping code to a lot of servers and they trust this project not to ship malicious code. So I will review everything before it goes out.

**Comment by christhekeele** [comment]
I've been on tangents for the last year, too, but it looks like I'm coming back around to more user-based stuff and Authority is still my weapon of choice.

I'd love to be helpful, even if just in answering issues and reviewing requests.

**Comment by nathanl** [comment]
@christhekeele Yay! That would be awesome. :smile: Yes, and I think it should be capitalized. *Friends of Authority*.

@christhekeele and @binarypaladin, I hereby give you commit bits. Use them wisely. Like lightsabers, or something. :smile:

**Comment by sanemat** [comment]
Great! I'll contribute backward/forward compatibility :sunglasses:

**Comment by nathanl** [comment]
Yay! :)

**Comment by binarypaladin** [comment]
I just had a talk with our CEO and he's cool with us spending time to maintain the project. So I'll be able to at least pop in a bit of time a week to review stuff even as a matter of work. As such, I'll dig into the codebase. (Plus, there are a couple features I was thinking of adding anyway.)

**Comment by nathanl** [comment]
@binarypaladin Yay! :hand: :hand: :smile:
