### ISSUE TITLE
Instance level rules should rely on instance level default

### ISSUE THREAD

**Issue by youroff** [nathanl/authority#96]
As far as I see, all instance level rules fall back to class level rules and then self.default. It would be nice to have one more step: default method with resource accessible inside. Silly example:
```
class ArticleAuthorizer < ApplicationAuthorizer

  def self.default adj, user
    user.has_role? :writer
  end

  def default user
    user == resource.author
  end
end
```

**Comment by youroff** [comment]
Haha... Seems like someone's pull-request about this issue waits to be merged!

**Comment by nathanl** [comment]
Yep - https://github.com/nathanl/authority/pull/90

**Comment by christhekeele** [comment]
I'm adding this to the next planned version of Authority, as well.

**Comment by nathanl** [comment]
@youroff #90 is merged to master and will be in the next release. You can thank @paukul for this feature, which he wasn't sure would be useful to anyone else. :smile:

**Comment by youroff** [comment]
Awesome! Thanks @paukul :+1:
