### ISSUE TITLE
Use of :all_actions and :actions simultaneously

### ISSUE THREAD

**Issue by youroff** [nathanl/authority#98]
force_action overwrites previously set actions. Would be good to swap these calls to be able to set default permission and then refine it with actions. Sounds reasonable?

```
      def authorize_actions_for(resource_or_finder, options = {})
        self.authority_resource = resource_or_finder
        add_actions(options.fetch(:actions, {}))
        force_action(options[:all_actions]) if options[:all_actions]
        before_filter :run_authorization_check, options
      end
```

**Comment by christhekeele** [comment]
Can you elaborate with some more controller sample code and the desired behaviour?

**Comment by youroff** [comment]
I did this change as monkey patch, and here how I use it:
```
  authorize_actions_for Recon::Item, all_actions: :manage, actions: {
    next:   'manage',
    cancel: 'manage',
    sales:  'observe'
  }
```
However, in this particular example I need it only to authorize all instance level requests by one method manageable_by? (which is also custom), so when we have `instance level default` pull-request merged, this example become irrelevant.

What I feel would better is the ability to use `all_actions` as a wildcard. Right now it just overwrites actions map, but it could set a fallback for it. So there might be 3 steps during authorization call:
1) Check if there's an action in user customized map.
2) Check if there's all_actions fallback.
3) Check action in default map.
4) raise exception...

**Comment by christhekeele** [comment]
I think I see what you're getting at. I've never before used the `:all_actions` feature myself, but I get what it's there for now–and how you expected it to behave differently.

I'll add this to the discussion of the next version. Thanks!

**Comment by nathanl** [comment]
Authority is now unmaintained - see README.
